# Generated by Django 5.2.11 on 2026-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "total_posts",
                    models.PositiveIntegerField(default=0, verbose_name="Total Posts"),
                ),
                (
                    "total_comments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Comments"
                    ),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(default=0, verbose_name="Total Users"),
                ),
                (
                    "published_posts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Published Posts"
                    ),
                ),
                (
                    "new_comments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="New Comments (last 24h)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Stat",
                "verbose_name_plural": "Daily Stats",
                "ordering": ["-date"],
            },
        ),
    ]
