# Generated by Django 5.2.11 on 2026-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, the Beat task will auto-publish this post at the given time.",
                null=True,
                verbose_name="Publish at",
            ),
        ),
    ]
